//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public System.DateTime RegTime { get; set; }
        public bool Seen { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public int RemoteUserID { get; set; }
    
        public virtual RemoteUser RemoteUser { get; set; }
    }
}
