//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaX
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;

    [SettingsSerializeAs(SettingsSerializeAs.Xml)]
    public partial class RemoteUser
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string RealName { get; set; }
    }
}
