//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaXCentral
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public int PassengerID { get; set; }
        public int ShiftID { get; set; }
        public int UserID { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual User User { get; set; }
    }
}
