//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaXCentral
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VisaXCenterNew : DbContext
    {
        public VisaXCenterNew()
            : base("name=VisaXCenterNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<RemotePassenger> RemotePassengers { get; set; }
        public virtual DbSet<RemoteRequest> RemoteRequests { get; set; }
        public virtual DbSet<RemoteShift> RemoteShifts { get; set; }
        public virtual DbSet<RemoteUser> RemoteUsers { get; set; }
    }
}
