//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaXCentral
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteShift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RemoteShift()
        {
            this.RemoteRequests = new HashSet<RemoteRequest>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public byte ShiftNum { get; set; }
        public int RemoteUserID { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoteRequest> RemoteRequests { get; set; }
        public virtual RemoteUser RemoteUser { get; set; }
    }
}
